apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: wordpress-v2
  labels:
    app: mysql
type: Opaque
stringData:
  # MySQL root 密码
  MYSQL_ROOT_PASSWORD: "rootpassword123"
  # WordPress 使用的数据库密码
  MYSQL_PASSWORD: "wordpress123"
  # WordPress 使用的数据库名
  MYSQL_DATABASE: "wordpress"
  # WordPress 使用的数据库用户
  MYSQL_USER: "wpuser"
